import type { CampaignStage } from "./types"

export const CAMPAIGN_STAGES: CampaignStage[] = [
  {
    id: "rua-periferia",
    tier: "rua",
    name: "Botecos da Rua",
    shortDescription: "O começo da jornada, na base da coragem, fumaça e cadeira de plástico.",
    mapLabel: "Rua da Periferia",
    cutsceneIntro: "Você começa onde quase ninguém repara. Mesa torta, truco alto e respeito em disputa.",
    cutsceneOutro: "Seu nome começa a circular. Ainda é pouco, mas já não passa despercebido.",
    reward: { coins: 150, unlockIds: ["table-boteco-rua"] },
    venues: [
      {
        id: "bar-do-negao",
        name: "Bar do Negão",
        districtLabel: "Rua 12",
        visualTheme: "boteco-raiz",
        atmosphere: "Paredes gastas, piso engordurado e televisão velha ligada no fundo.",
        matchesToClear: 3,
        variant: "MINEIRO",
        difficulty: { aiLevel: 1, aggression: 1, trucoDiscipline: 1 },
        entryNarrative: "Aqui ninguém quer saber de fama. Só querem ver se você aguenta a pressão.",
        reward: { coins: 40 },
        monetizationHooks: { rewardedAdOfferId: "double-coins-street-1" },
      },
      {
        id: "esquina-do-paulista",
        name: "Esquina do Paulista",
        districtLabel: "Rua 18",
        visualTheme: "boteco-raiz",
        atmosphere: "Mesas de metal, copos batendo e barulho de dominó.",
        matchesToClear: 4,
        variant: "PAULISTA",
        difficulty: { aiLevel: 1, aggression: 2, trucoDiscipline: 1 },
        entryNarrative: "Você cruza a rua e encontra um jogo mais falado, mais provocativo e mais rápido.",
        reward: { coins: 55 },
      },
    ],
  },
  {
    id: "circuito-bairro",
    tier: "bairro",
    name: "Circuito do Bairro",
    shortDescription: "A vizinhança já conhece sua cara. Agora começa a cobrança por resultado.",
    mapLabel: "Bairro",
    unlockRequirement: "Vencer os botecos da rua",
    cutsceneIntro: "Os campeonatos de bairro são pequenos, mas a rivalidade já é levada a sério.",
    cutsceneOutro: "Você deixa de ser promessa de rua e vira referência local.",
    reward: { coins: 300 },
    venues: [
      {
        id: "mercearia-central",
        name: "Mercearia Central",
        districtLabel: "Miolo do Bairro",
        visualTheme: "bairro-popular",
        atmosphere: "Mais organizado, mas ainda carregado de provocação e histórias antigas.",
        matchesToClear: 5,
        variant: "MINEIRO",
        difficulty: { aiLevel: 2, aggression: 2, trucoDiscipline: 2 },
        entryNarrative: "Quem vence aqui começa a entrar no radar das duplas mais experientes.",
        reward: { coins: 80 },
      },
      {
        id: "arena-do-largo",
        name: "Arena do Largo",
        districtLabel: "Largo do Bairro",
        visualTheme: "bairro-noite",
        atmosphere: "Luzes improvisadas, música ao vivo e plateia espremida ao redor das mesas.",
        matchesToClear: 6,
        variant: "PAULISTA",
        difficulty: { aiLevel: 2, aggression: 3, trucoDiscipline: 2 },
        entryNarrative: "O jogo fica mais quente e a arquibancada improvisada já pressiona.",
        reward: { coins: 100 },
      },
    ],
  },
  {
    id: "zonas-da-cidade",
    tier: "zona",
    name: "Conquista das Zonas",
    shortDescription: "Zona Norte, Leste, Sul e Centro. Cada região tem sua própria lenda.",
    mapLabel: "Zonas da Cidade",
    unlockRequirement: "Dominar o circuito do bairro",
    cutsceneIntro: "Agora o mapa cresce. Cada zona tem estética, público e rivais próprios.",
    cutsceneOutro: "Você deixa de ser jogador de bairro e se torna nome forte da cidade inteira.",
    reward: { coins: 550 },
    venues: [
      {
        id: "zona-norte-garagem",
        name: "Garage Norte",
        districtLabel: "Zona Norte",
        visualTheme: "zona-norte-industrial",
        atmosphere: "Ferro, concreto, fumaça e partidas duríssimas.",
        matchesToClear: 4,
        variant: "MINEIRO",
        difficulty: { aiLevel: 3, aggression: 3, trucoDiscipline: 2 },
        entryNarrative: "Na Zona Norte, a intimidação faz parte do ritual.",
        reward: { coins: 110 },
      },
      {
        id: "zona-leste-quintal",
        name: "Quintal da Leste",
        districtLabel: "Zona Leste",
        visualTheme: "zona-leste-festival",
        atmosphere: "Partidas cheias, muita conversa e estilo agressivo.",
        matchesToClear: 5,
        variant: "PAULISTA",
        difficulty: { aiLevel: 3, aggression: 4, trucoDiscipline: 3 },
        entryNarrative: "Na Leste, a partida parece festa. Mas ninguém alivia.",
        reward: { coins: 130 },
      },
      {
        id: "centro-subsolo",
        name: "Subsolo do Centro",
        districtLabel: "Centro",
        visualTheme: "centro-underground",
        atmosphere: "Bar escondido, iluminação baixa e jogadores calculistas.",
        matchesToClear: 6,
        variant: "MINEIRO",
        difficulty: { aiLevel: 3, aggression: 2, trucoDiscipline: 4 },
        entryNarrative: "No Centro, o truco é mais frio, técnico e implacável.",
        reward: { coins: 150 },
      },
      {
        id: "zona-sul-salao",
        name: "Salão da Sul",
        districtLabel: "Zona Sul",
        visualTheme: "zona-sul-premium",
        atmosphere: "Um boteco mais arrumado, mas ainda com alma de esquina.",
        matchesToClear: 5,
        variant: "PAULISTA",
        difficulty: { aiLevel: 3, aggression: 3, trucoDiscipline: 4 },
        entryNarrative: "Na Zona Sul, o visual melhora, mas a malandragem continua.",
        reward: { coins: 150 },
        monetizationHooks: { cosmeticPreviewId: "table-cassino-mundial" },
      },
    ],
  },
  {
    id: "campeonato-da-cidade",
    tier: "cidade",
    name: "Campeonato da Cidade",
    shortDescription: "Os melhores das zonas se encontram num circuito urbano já com cara de evento grande.",
    mapLabel: "Cidade",
    unlockRequirement: "Dominar as zonas da cidade",
    cutsceneIntro: "A rivalidade sai dos territórios e entra num palco que a cidade toda acompanha.",
    cutsceneOutro: "Agora seu nome ecoa pela cidade inteira. O próximo passo é levar isso para o estado.",
    reward: { coins: 700 },
    venues: [
      {
        id: "centro-de-convencoes-urbano",
        name: "Centro de Convenções Urbano",
        districtLabel: "Circuito da Cidade",
        visualTheme: "cidade-evento",
        atmosphere: "Evento estruturado, mais público e rivais conhecidos em toda a capital.",
        matchesToClear: 6,
        variant: "PAULISTA",
        difficulty: { aiLevel: 4, aggression: 3, trucoDiscipline: 4 },
        entryNarrative: "A cidade quer saber se você era moda passageira ou nome de verdade.",
        reward: { coins: 180 },
      },
    ],
  },
  {
    id: "campeonato-estadual",
    tier: "estado",
    name: "Campeonato Estadual",
    shortDescription: "O jogo sai dos bairros e vira assunto de tradição regional.",
    mapLabel: "Estado",
    unlockRequirement: "Vencer o campeonato da cidade",
    cutsceneIntro: "A partir daqui, cada mesa carrega reputação, tradição e história.",
    cutsceneOutro: "Seu estilo ganha identidade própria. Agora o país começa a observar.",
    reward: { coins: 800 },
    venues: [
      {
        id: "ginasio-estadual",
        name: "Ginásio Estadual",
        districtLabel: "Capital",
        visualTheme: "estadual-classico",
        atmosphere: "Evento organizado, narrador local e rivais experientes.",
        matchesToClear: 6,
        variant: "PAULISTA",
        difficulty: { aiLevel: 4, aggression: 3, trucoDiscipline: 4 },
        entryNarrative: "A brincadeira acabou. Agora o jogo tem fama e cobrança.",
        reward: { coins: 220 },
      },
    ],
  },
  {
    id: "campeonato-nacional",
    tier: "nacional",
    name: "Campeonato Nacional",
    shortDescription: "Seu nome já representa mais que um bairro. Agora vale o país inteiro.",
    mapLabel: "Brasil",
    unlockRequirement: "Vencer o estadual",
    cutsceneIntro: "Diferentes estilos do país se encontram numa disputa de reputação nacional.",
    cutsceneOutro: "Você passa a ser tratado como elite do circuito.",
    reward: { coins: 1200 },
    venues: [
      {
        id: "arena-nacional",
        name: "Arena Nacional",
        districtLabel: "Capital Federal",
        visualTheme: "nacional-broadcast",
        atmosphere: "Plateia grande, transmissão e adversários preparados.",
        matchesToClear: 7,
        variant: "PAULISTA",
        difficulty: { aiLevel: 4, aggression: 4, trucoDiscipline: 4 },
        entryNarrative: "Agora cada erro pesa e cada vitória vira manchete.",
        reward: { coins: 300 },
      },
    ],
  },
  {
    id: "circuito-panamericano",
    tier: "panamericano",
    name: "Circuito Panamericano",
    shortDescription: "A jornada fica internacional, com estilos, sotaques e apresentações novas.",
    mapLabel: "Américas",
    unlockRequirement: "Vencer o nacional",
    cutsceneIntro: "O jogo ganha espetáculo, diversidade e rivais de escolas diferentes.",
    cutsceneOutro: "Você deixa de ser estrela nacional e vira nome continental.",
    reward: { coins: 1600 },
    venues: [
      {
        id: "centro-panamericano",
        name: "Centro Panamericano",
        districtLabel: "Capital Internacional",
        visualTheme: "panamericano-show",
        atmosphere: "Visual mais moderno, produção maior e atmosfera de evento continental.",
        matchesToClear: 5,
        variant: "MINEIRO",
        difficulty: { aiLevel: 4, aggression: 4, trucoDiscipline: 5 },
        entryNarrative: "A tradição local encontra o show internacional.",
        reward: { coins: 360 },
      },
    ],
  },
  {
    id: "jogos-mundiais",
    tier: "jogos-mundiais",
    name: "Jogos Mundiais",
    shortDescription: "A consagração esportiva antes da reta final do glamour.",
    mapLabel: "Jogos Mundiais",
    unlockRequirement: "Vencer o circuito panamericano",
    cutsceneIntro: "Cerimônia, bandeiras, delegações e pressão de desempenho máximo.",
    cutsceneOutro: "Você entra no seleto grupo que pode sonhar com o topo do mundo.",
    reward: { coins: 2000 },
    venues: [
      {
        id: "arena-das-delegacoes",
        name: "Arena das Delegações",
        districtLabel: "Cidade-Sede",
        visualTheme: "mundial-esportivo",
        atmosphere: "Organização impecável e tensão quase cerimonial.",
        matchesToClear: 4,
        variant: "PAULISTA",
        difficulty: { aiLevel: 5, aggression: 4, trucoDiscipline: 5 },
        entryNarrative: "O erro agora não é só derrota. É vexame em escala global.",
        reward: { coins: 450 },
      },
    ],
  },
  {
    id: "mundial-cassino",
    tier: "mundial",
    name: "Mundial do Cassino",
    shortDescription: "O ápice da campanha principal: luxo, status e as melhores duplas do planeta.",
    mapLabel: "Mundial",
    unlockRequirement: "Vencer os Jogos Mundiais",
    cutsceneIntro: "A fumaça do boteco ficou para trás. Agora é lustre, veludo e silêncio tenso.",
    cutsceneOutro: "Você provou tudo o que precisava no mundo real.",
    reward: { coins: 2800, unlockIds: ["table-cassino-mundial"] },
    venues: [
      {
        id: "mesa-principal-do-mundial",
        name: "Mesa Principal",
        districtLabel: "Cassino Mundial",
        visualTheme: "cassino-luxo",
        atmosphere: "Mesa nobre, iluminação teatral e público seleto.",
        matchesToClear: 5,
        variant: "PAULISTA",
        difficulty: { aiLevel: 5, aggression: 5, trucoDiscipline: 5 },
        entryNarrative: "Chegar até aqui foi raro. Vencer aqui é lendário.",
        reward: { coins: 700 },
      },
    ],
  },
  {
    id: "intergalactico",
    tier: "bonus",
    name: "Circuito Intergaláctico",
    shortDescription: "Conteúdo bônus pós-campanha, estilizado e exagerado, sem compromisso com realismo.",
    mapLabel: "Bônus",
    unlockRequirement: "Concluir o mundial",
    cutsceneIntro: "Quando o mundo já não bastava, sobrou desafiar o impossível.",
    cutsceneOutro: "Você venceu até onde o truco deveria ser impossível.",
    reward: { coins: 5000, unlockIds: ["cards-intergalactico"] },
    venues: [
      {
        id: "orbita-da-lua",
        name: "Órbita da Lua",
        districtLabel: "Setor Lunar",
        visualTheme: "sci-fi-lunar",
        atmosphere: "Mesa holográfica, neon e rivais caricatos de outro nível.",
        matchesToClear: 7,
        variant: "MINEIRO",
        difficulty: { aiLevel: 5, aggression: 5, trucoDiscipline: 5 },
        entryNarrative: "Agora vale espetáculo. O mundo já ficou pequeno.",
        reward: { coins: 1000 },
      },
    ],
  },
]
