import { Suspense, lazy, useEffect, useMemo, useState } from "react"
import { useGameSession } from "./app/useGameSession"
import botecoSceneBgAsset from "./assets/boteco/boteco-scene-bg.png"
import cardFaceAgedPaperAsset from "./assets/cards/card-face-aged-paper.png"

const TableSection = lazy(async () => {
  const mod = await import("./app/AppSections")
  return { default: mod.TableSection }
})
const HandStatusPanel = lazy(async () => {
  const mod = await import("./app/AppSections")
  return { default: mod.HandStatusPanel }
})
const CampaignPanel = lazy(async () => {
  const mod = await import("./app/AppSections")
  return { default: mod.CampaignPanel }
})
const LogsPanel = lazy(async () => {
  const mod = await import("./app/AppSections")
  return { default: mod.LogsPanel }
})

type GameplayLayoutMode = "regular" | "compact"

function shouldUseTightSidebar(): boolean {
  if (typeof window === "undefined") {
    return false
  }

  return window.innerHeight < 780
}

function getGameplayLayoutMode(): GameplayLayoutMode {
  if (typeof window === "undefined") {
    return "regular"
  }

  return window.innerWidth < 1440 || window.innerHeight < 860 ? "compact" : "regular"
}

function App() {
  const [layoutMode, setLayoutMode] = useState<GameplayLayoutMode>(getGameplayLayoutMode)
  const [useTightSidebar, setUseTightSidebar] = useState(shouldUseTightSidebar)

  useEffect(() => {
    const handleResize = () => {
      setLayoutMode(getGameplayLayoutMode())
      setUseTightSidebar(shouldUseTightSidebar())
    }

    window.addEventListener("resize", handleResize)
    return () => window.removeEventListener("resize", handleResize)
  }, [])

  const {
    activeVariant,
    canHumanAdvisePartner,
    canHumanRaiseTruco,
    canHumanRespondToTruco,
    canPlayHumanCard,
    canRequestTruco,
    campaignCompleted,
    campaignSummary,
    currentCampaignStage,
    currentCampaignVenue,
    currentTurnLabel,
    currentVenueWins,
    debugModeEnabled,
    debugVenueId,
    debugVenueOptions,
    dealAnimationNonce,
    eventMessage,
    handScoreLabel,
    handState,
    handleAcceptTruco,
    handleCloseCharacterSelect,
    handlePartnerAdvice,
    handleCopyLogs,
    handleOpenCharacterSelect,
    handlePlayCard,
    handleRaiseTruco,
    handleRequestTruco,
    handleResetCampaign,
    handleRunFromTruco,
    handleSelectNextCharacter,
    handleSelectPreviousCharacter,
    handleStartHand,
    lastPlayedPlayerId,
    logs,
    matchScoreLabel,
    matchState,
    menuScreen,
    opponentCharacters,
    player1,
    playerProfile,
    selectedCharacter,
    selectedCharacterIndex,
    selectedPartnerCharacter,
    selectableCharacters,
    setVariant,
    setDebugVenueId,
    speechBubble,
    statusMessage,
    tableByPlayer,
    variantSelectionDisabled,
    handleConfirmCharacterSelect,
  } = useGameSession()

  const isCompactLayout = layoutMode === "compact"

  const responsiveStyles = useMemo<Record<string, React.CSSProperties>>(
    () => ({
      ...styles,
      gameViewportFrame: {
        ...styles.gameViewportFrame,
        width: isCompactLayout
          ? "min(100%, calc((100dvh - 228px) * 2.16))"
          : styles.gameViewportFrame.width,
        minHeight: isCompactLayout ? "min(400px, 64dvh)" : styles.gameViewportFrame.minHeight,
        maxHeight: isCompactLayout ? "73dvh" : styles.gameViewportFrame.maxHeight,
      },
      gameViewport: {
        ...styles.gameViewport,
        gridTemplateColumns: isCompactLayout
          ? "clamp(206px, 21vw, 234px) minmax(0, 1fr) clamp(160px, 16.2vw, 182px)"
          : "clamp(220px, 18.5vw, 252px) minmax(0, 1fr) clamp(168px, 14.2vw, 188px)",
        gap: isCompactLayout ? "clamp(5px, 0.55vw, 8px)" : styles.gameViewport.gap,
      },
      gameLeftRail: {
        ...styles.gameLeftRail,
        justifyItems: "stretch",
      },
      gameSidebarColumn: {
        ...styles.gameSidebarColumn,
        justifyItems: "stretch",
      },
      scenePanel: {
        ...styles.scenePanel,
        width: "100%",
        boxSizing: "border-box",
      },
      scorePadCard: {
        ...styles.scorePadCard,
        width: "100%",
        boxSizing: "border-box",
      },
      scorePadCardSurface: {
        ...styles.scorePadCardSurface,
        width: isCompactLayout ? "min(100%, 156px)" : "min(100%, 174px)",
        maxHeight: isCompactLayout ? "94%" : "96%",
      },
      gameMainColumn: {
        ...styles.gameMainColumn,
        gridTemplateRows: isCompactLayout ? "minmax(0, 1fr) minmax(78px, auto)" : "minmax(0, 1fr) auto",
      },
      tableSurface: {
        ...styles.tableSurface,
        transform: isCompactLayout ? "scale(1.04)" : "scale(1.08)",
        maxWidth: isCompactLayout ? "98%" : "100%",
      },
      playerCardsBlock: {
        ...styles.playerCardsBlock,
        width: "100%",
        boxSizing: "border-box",
        minHeight: isCompactLayout
          ? "clamp(74px, 6.6vw, 90px)"
          : styles.playerCardsBlock.minHeight,
      },
      tableHudSidebar: {
        ...styles.tableHudSidebar,
        width: "100%",
        boxSizing: "border-box",
        gridTemplateRows: useTightSidebar
          ? "max-content max-content"
          : isCompactLayout
            ? "max-content max-content"
            : "max-content max-content",
        gap: useTightSidebar ? "clamp(6px, 0.5vw, 8px)" : styles.tableHudSidebar.gap,
        alignContent: "center",
        alignItems: "center",
      },
      tableHudStats: {
        ...styles.tableHudStats,
        width: isCompactLayout ? "90%" : "88%",
        padding: useTightSidebar
          ? "clamp(8px, 0.62vw, 10px) clamp(10px, 0.82vw, 11px)"
          : styles.tableHudStats.padding,
        gap: useTightSidebar ? "clamp(5px, 0.42vw, 7px)" : styles.tableHudStats.gap,
        minHeight: useTightSidebar ? "clamp(116px, 14vw, 138px)" : undefined,
        height: useTightSidebar ? "auto" : styles.tableHudStats.height,
      },
      inGameActionsCard: {
        ...styles.inGameActionsCard,
        width: isCompactLayout ? "90%" : "88%",
        marginTop: useTightSidebar ? "clamp(4px, 0.35vw, 6px)" : styles.inGameActionsCard.marginTop,
        gap: useTightSidebar ? "clamp(6px, 0.48vw, 8px)" : styles.inGameActionsCard.gap,
      },
      tableCenterArea: {
        ...styles.tableCenterArea,
        minHeight: isCompactLayout ? "clamp(300px, 38dvh, 340px)" : styles.tableCenterArea.minHeight,
      },
      tableHudStatLineCentered: {
        ...styles.tableHudStatLineCentered,
        gap: useTightSidebar ? "clamp(2px, 0.18vw, 3px)" : styles.tableHudStatLineCentered.gap,
      },
      tableHudStatLabelCentered: {
        ...styles.tableHudStatLabelCentered,
        fontSize: useTightSidebar ? "clamp(7px, 0.62vw, 8px)" : styles.tableHudStatLabelCentered.fontSize,
      },
      tableHudStatValueCentered: {
        ...styles.tableHudStatValueCentered,
        fontSize: useTightSidebar ? "clamp(10px, 0.92vw, 13px)" : styles.tableHudStatValueCentered.fontSize,
        lineHeight: useTightSidebar ? 1.05 : styles.tableHudStatValueCentered.lineHeight,
      },
      inGameActionsRow: {
        ...styles.inGameActionsRow,
        gap: useTightSidebar ? "clamp(5px, 0.42vw, 6px)" : styles.inGameActionsRow.gap,
      },
      inGameActionsGrid: {
        ...styles.inGameActionsGrid,
        gap: useTightSidebar ? "clamp(5px, 0.42vw, 6px)" : styles.inGameActionsGrid.gap,
      },
      trucoPrimaryButton: {
        ...styles.trucoPrimaryButton,
        minHeight: useTightSidebar ? "clamp(30px, 2.3vw, 34px)" : styles.trucoPrimaryButton.minHeight,
        padding: useTightSidebar
          ? "clamp(4px, 0.34vw, 6px) clamp(10px, 0.82vw, 12px)"
          : styles.trucoPrimaryButton.padding,
        fontSize: useTightSidebar ? "clamp(9px, 0.78vw, 10px)" : styles.trucoPrimaryButton.fontSize,
      },
      trucoSecondaryButton: {
        ...styles.trucoSecondaryButton,
        minHeight: useTightSidebar ? "clamp(30px, 2.3vw, 34px)" : styles.trucoSecondaryButton.minHeight,
        padding: useTightSidebar
          ? "clamp(4px, 0.34vw, 6px) clamp(10px, 0.82vw, 12px)"
          : styles.trucoSecondaryButton.padding,
        fontSize: useTightSidebar ? "clamp(9px, 0.78vw, 10px)" : styles.trucoSecondaryButton.fontSize,
      },
    }),
    [isCompactLayout, useTightSidebar]
  )

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <header style={styles.header}>
          <div>
            <h1 style={styles.title}>Truco Game</h1>
            <p style={styles.subtitle}>
              Mesa jogável · fluxo passo a passo · foco em clareza visual
            </p>
          </div>
        </header>

        <Suspense fallback={<div style={responsiveStyles.loadingCard}>Carregando mesa...</div>}>
          <TableSection
            activeVariant={activeVariant}
            campaignCompleted={campaignCompleted}
            handState={handState}
            matchState={matchState}
            currentCampaignVenue={currentCampaignVenue}
            debugModeEnabled={debugModeEnabled}
            debugVenueId={debugVenueId}
            debugVenueOptions={debugVenueOptions}
            dealAnimationNonce={dealAnimationNonce}
            menuScreen={menuScreen}
            opponentCharacters={opponentCharacters}
            selectedCharacter={selectedCharacter}
            selectedCharacterIndex={selectedCharacterIndex}
            selectedPartnerCharacter={selectedPartnerCharacter}
            selectableCharacters={selectableCharacters}
            speechBubble={speechBubble}
            tableByPlayer={tableByPlayer}
            lastPlayedPlayerId={lastPlayedPlayerId}
            player1={player1}
            canRequestTruco={canRequestTruco}
            canHumanAdvisePartner={canHumanAdvisePartner}
            canHumanRaiseTruco={canHumanRaiseTruco}
            canHumanRespondToTruco={canHumanRespondToTruco}
            canPlayHumanCard={canPlayHumanCard}
            variantSelectionDisabled={variantSelectionDisabled}
            onChangeVariant={setVariant}
            onChangeDebugVenue={setDebugVenueId}
            onCloseCharacterSelect={handleCloseCharacterSelect}
            onConfirmCharacterSelect={handleConfirmCharacterSelect}
            onOpenCharacterSelect={handleOpenCharacterSelect}
            onResetCampaign={handleResetCampaign}
            onSelectNextCharacter={handleSelectNextCharacter}
            onSelectPreviousCharacter={handleSelectPreviousCharacter}
            onStart={handleStartHand}
            onRequestTruco={handleRequestTruco}
            onAcceptTruco={handleAcceptTruco}
            onAdvisePartner={handlePartnerAdvice}
            onRaiseTruco={handleRaiseTruco}
            onRunFromTruco={handleRunFromTruco}
            onPlayCard={handlePlayCard}
            styles={responsiveStyles}
          />
        </Suspense>

        <Suspense fallback={<div style={responsiveStyles.panelLoadingCard}>Carregando status...</div>}>
          <HandStatusPanel
            activeVariant={activeVariant}
            currentCampaignVenue={currentCampaignVenue}
            handState={handState}
            matchHandNumber={matchState?.handNumber ?? 1}
            matchScoreLabel={matchScoreLabel}
            handScoreLabel={handScoreLabel}
            currentTurnLabel={currentTurnLabel}
            statusMessage={statusMessage}
            eventMessage={eventMessage}
            styles={responsiveStyles}
          />
        </Suspense>

        <Suspense fallback={<div style={responsiveStyles.panelLoadingCard}>Carregando campanha...</div>}>
          <CampaignPanel
            campaignCompleted={campaignCompleted}
            currentCampaignStage={currentCampaignStage}
            currentCampaignVenue={currentCampaignVenue}
            currentVenueWins={currentVenueWins}
            campaignSummary={campaignSummary}
            playerProfile={playerProfile}
            onResetCampaign={handleResetCampaign}
            styles={responsiveStyles}
          />
        </Suspense>

        <Suspense fallback={<div style={responsiveStyles.panelLoadingCard}>Carregando logs...</div>}>
          <LogsPanel logs={logs} onCopyLogs={handleCopyLogs} styles={responsiveStyles} />
        </Suspense>
      </div>
    </div>
  )
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "linear-gradient(180deg, #e7ecef 0%, #d8e1e8 100%)",
    padding: "24px",
    boxSizing: "border-box",
    fontFamily: "Arial, sans-serif",
    color: "#111827",
  },
  container: {
    maxWidth: "1280px",
    margin: "0 auto",
  },
  header: {
    marginBottom: "16px",
  },
  title: {
    margin: 0,
    fontSize: "42px",
    lineHeight: 1.1,
  },
  subtitle: {
    margin: "8px 0 0 0",
    color: "#4b5563",
    fontSize: "16px",
  },
  topGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1.1fr",
    gap: "16px",
    marginBottom: "16px",
  },
  panelCard: {
    background: "#ffffff",
    border: "1px solid #d8dee6",
    borderRadius: "18px",
    padding: "18px",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
  },
  progressionCard: {
    background: "#ffffff",
    border: "1px solid #d8dee6",
    borderRadius: "20px",
    padding: "18px",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
    marginBottom: "16px",
  },
  loadingCard: {
    minHeight: "320px",
    display: "grid",
    placeItems: "center",
    borderRadius: "20px",
    border: "1px solid #d8dee6",
    background: "#ffffff",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
    fontSize: "16px",
    fontWeight: 700,
    color: "#475569",
  },
  panelLoadingCard: {
    minHeight: "96px",
    display: "grid",
    placeItems: "center",
    borderRadius: "18px",
    border: "1px solid #d8dee6",
    background: "#ffffff",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
    fontSize: "14px",
    fontWeight: 700,
    color: "#64748b",
    marginTop: "16px",
  },
  progressionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "16px",
    flexWrap: "wrap",
  },
  progressionSubtitle: {
    fontSize: "14px",
    color: "#64748b",
    marginTop: "4px",
  },
  progressionBadge: {
    borderRadius: "999px",
    background: "#111827",
    color: "#fff",
    padding: "10px 14px",
    fontSize: "13px",
    fontWeight: 700,
  },
  progressionSummaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: "10px",
    marginBottom: "16px",
  },
  campaignStatusBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    borderRadius: "16px",
    border: "1px solid #dbe4ed",
    background: "#f8fafc",
    padding: "14px",
    marginBottom: "12px",
  },
  campaignStatusPrimary: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  campaignStatusTitle: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#0f172a",
  },
  campaignStatusText: {
    fontSize: "14px",
    color: "#475569",
  },
  campaignStatusMeta: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    fontSize: "13px",
    fontWeight: 700,
    color: "#0f172a",
  },
  campaignButtonsRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "16px",
    flexWrap: "wrap",
  },
  progressionBody: {
    display: "grid",
    gridTemplateColumns: "1.4fr 0.9fr",
    gap: "16px",
    alignItems: "start",
  },
  progressionColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  progressionColumnTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#0f172a",
  },
  stageGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "12px",
  },
  stageCard: {
    borderRadius: "16px",
    border: "1px solid #dbe4ed",
    background: "#f8fafc",
    padding: "14px",
  },
  stageCardActive: {
    background: "#ecfdf5",
    border: "1px solid #86efac",
  },
  stageCardCompleted: {
    background: "#eff6ff",
    border: "1px solid #93c5fd",
  },
  stageCardTopRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "10px",
    marginBottom: "10px",
  },
  stageCardTitle: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#0f172a",
  },
  stageCardTier: {
    fontSize: "12px",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginTop: "4px",
    fontWeight: 700,
  },
  stageCardMapLabel: {
    borderRadius: "999px",
    background: "#e2e8f0",
    color: "#334155",
    padding: "6px 10px",
    fontSize: "12px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  stageCardText: {
    fontSize: "14px",
    color: "#475569",
    lineHeight: 1.45,
    marginBottom: "12px",
  },
  stageCardMetaRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    fontSize: "13px",
    color: "#0f172a",
    fontWeight: 700,
  },
  roadmapBox: {
    borderRadius: "16px",
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    padding: "14px",
  },
  roadmapTitle: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#9a3412",
    marginBottom: "6px",
  },
  roadmapText: {
    margin: 0,
    fontSize: "14px",
    lineHeight: 1.5,
    color: "#7c2d12",
  },
  panelTitle: {
    fontSize: "20px",
    fontWeight: 700,
    marginBottom: "14px",
  },
  controlRow: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  label: {
    fontWeight: 700,
  },
  select: {
    padding: "10px 12px",
    borderRadius: "10px",
    border: "1px solid #cbd5e1",
    minWidth: "220px",
    fontSize: "16px",
    background: "#fff",
  },
  buttonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "12px",
    marginBottom: "16px",
  },
  primaryButton: {
    padding: "12px 18px",
    borderRadius: "12px",
    border: "none",
    background: "#111827",
    color: "#fff",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: 700,
  },
  secondaryButton: {
    padding: "12px 18px",
    borderRadius: "12px",
    border: "1px solid #cbd5e1",
    background: "#fff",
    color: "#111827",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: 700,
  },
  disabledButton: {
    opacity: 0.72,
    filter: "saturate(0.82)",
    cursor: "not-allowed",
  },
  helpBox: {
    borderRadius: "14px",
    padding: "14px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  helpTitle: {
    fontWeight: 700,
    marginBottom: "8px",
  },
  helpText: {
    margin: 0,
    color: "#475569",
    lineHeight: 1.5,
    fontSize: "15px",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "10px",
    marginBottom: "14px",
  },
  infoBox: {
    borderRadius: "14px",
    padding: "12px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    minHeight: "72px",
    boxSizing: "border-box",
  },
  infoBoxLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#64748b",
    marginBottom: "6px",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  infoBoxValue: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#0f172a",
  },
  statusBanner: {
    marginBottom: "12px",
    padding: "14px",
    borderRadius: "14px",
    background: "#eef6ff",
    border: "1px solid #cfe2ff",
  },
  statusBannerLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#375a7f",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "6px",
  },
  statusBannerText: {
    fontSize: "17px",
    fontWeight: 700,
  },
  eventBanner: {
    marginBottom: "12px",
    padding: "14px",
    borderRadius: "14px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  eventBannerFinished: {
    background: "#ecfdf5",
    border: "1px solid #bbf7d0",
  },
  eventBannerLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "6px",
  },
  eventBannerText: {
    fontSize: "16px",
    fontWeight: 700,
  },
  teamLegendRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  teamLegendBox: {
    flex: 1,
    minWidth: "220px",
    borderRadius: "12px",
    padding: "10px 12px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    fontSize: "14px",
  },
  tablePanel: {
    background: "#ffffff",
    border: "1px solid #d8dee6",
    borderRadius: "20px",
    padding: "18px",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
    marginBottom: "16px",
  },
  gameHudLayout: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  tableHudSurface: {
    backgroundImage: `linear-gradient(180deg, rgba(16, 10, 7, 0.42) 0%, rgba(10, 7, 5, 0.5) 100%), url(${botecoSceneBgAsset})`,
    backgroundSize: "cover, cover",
    backgroundPosition: "center, center",
    backgroundRepeat: "no-repeat, no-repeat",
    borderRadius: "26px",
    padding: "clamp(10px, 1.4vw, 16px)",
    border: "4px solid #23170f",
    boxShadow: "inset 0 0 0 2px rgba(255,255,255,0.05)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  gameViewportFrame: {
    width: "min(100%, calc((100vh - 240px) * 2.16))",
    maxWidth: "100%",
    aspectRatio: "19.5 / 9",
    minHeight: "min(420px, 68vh)",
    maxHeight: "76vh",
    margin: "0 auto",
    display: "flex",
    overflow: "hidden",
    borderRadius: "22px",
  },
  gameViewport: {
    display: "grid",
    gridTemplateColumns: "minmax(148px, 0.24fr) minmax(0, 1fr) minmax(126px, 0.2fr)",
    gap: "clamp(6px, 0.75vw, 10px)",
    alignItems: "stretch",
    width: "100%",
    height: "100%",
    minHeight: 0,
  },
  gameLeftRail: {
    display: "grid",
    gridTemplateRows: "max-content minmax(0, 1fr)",
    gap: "clamp(5px, 0.55vw, 7px)",
    minWidth: 0,
    minHeight: 0,
    alignItems: "stretch",
    overflow: "hidden",
  },
  gameMainColumn: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    gap: "clamp(3px, 0.34vw, 5px)",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  gameSidebarColumn: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  scenePanel: {
    borderRadius: "22px",
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.03)",
    padding: "clamp(7px, 0.62vw, 9px)",
    boxShadow: "none",
    color: "#f7ede1",
    alignSelf: "start",
  },
  scenePanelTitle: {
    fontSize: "clamp(9px, 0.74vw, 11px)",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.09em",
    color: "#d9c6aa",
    marginBottom: "6px",
    textAlign: "center",
  },
  rosterGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "clamp(3px, 0.24vw, 5px) clamp(6px, 0.52vw, 8px)",
    alignItems: "start",
  },
  rosterCard: {
    borderRadius: "16px",
    background: "transparent",
    border: "1px solid transparent",
    padding: "clamp(2px, 0.2vw, 4px) clamp(2px, 0.2vw, 4px)",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(2px, 0.16vw, 3px)",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: "clamp(90px, 7.8vw, 106px)",
    boxShadow: "none",
  },
  rosterCardHuman: {
    border: "1px solid transparent",
    boxShadow: "none",
  },
  rosterAvatar: {
    width: "clamp(60px, 4.55vw, 70px)",
    height: "clamp(60px, 4.55vw, 70px)",
    borderRadius: "18px",
    background: "linear-gradient(180deg, #8a745d 0%, #4a392c 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(12px, 1vw, 15px)",
    fontWeight: 800,
    color: "#fff7ed",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.08)",
    overflow: "hidden",
    border: "1px solid rgba(240, 226, 206, 0.45)",
  },
  rosterAvatarImage: {
    width: "118%",
    height: "118%",
    objectFit: "cover",
    objectPosition: "center 22%",
    display: "block",
    transform: "scale(1.12)",
  },
  rosterName: {
    fontSize: "clamp(8px, 0.8vw, 11px)",
    fontWeight: 800,
    color: "#fff7ed",
    textAlign: "center",
    lineHeight: 1.05,
    maxWidth: "100%",
  },
  scorePadCard: {
    display: "flex",
    minWidth: 0,
    minHeight: 0,
    borderRadius: "20px",
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.03)",
    boxShadow: "none",
    padding: "clamp(8px, 0.72vw, 10px)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
    width: "100%",
    height: "100%",
  },
  scorePadCardSurface: {
    width: "min(100%, 168px)",
    maxWidth: "100%",
    height: "auto",
    maxHeight: "96%",
    borderRadius: "18px",
    background: "linear-gradient(180deg, #f4ead7 0%, #ead9b8 100%)",
    backgroundSize: "cover",
    backgroundPosition: "center top",
    backgroundRepeat: "no-repeat",
    border: "1px solid rgba(126, 82, 43, 0.32)",
    color: "#2f241b",
    display: "flex",
    flexDirection: "column",
    aspectRatio: "314 / 390",
    minHeight: 0,
    padding: "3.2%",
    boxSizing: "border-box",
    alignSelf: "center",
    marginTop: 0,
    position: "relative",
    overflow: "hidden",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.36)",
  },
  scorePadGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gridTemplateRows: "1fr 1fr",
    minHeight: "100%",
    gap: 0,
    position: "relative",
    zIndex: 1,
    width: "100%",
  },
  scorePadCellTopLeft: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingTop: "18%",
    paddingLeft: "15%",
    paddingRight: "15%",
    minWidth: 0,
    transform: "translateY(22%)",
  },
  scorePadCellTopRight: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    paddingTop: "18%",
    paddingLeft: "15%",
    paddingRight: "15%",
    minWidth: 0,
    transform: "translateY(22%)",
  },
  scorePadCellBottomLeft: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "flex-start",
    paddingBottom: "14%",
    paddingLeft: "15%",
    paddingRight: "15%",
    minWidth: 0,
    transform: "translateY(-48%)",
  },
  scorePadCellBottomRight: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    paddingBottom: "14%",
    paddingLeft: "15%",
    paddingRight: "15%",
    minWidth: 0,
    transform: "translateY(-48%)",
  },
  scorePadLabel: {
    fontSize: "clamp(15px, 1rem, 17px)",
    lineHeight: 1,
    fontWeight: 900,
    letterSpacing: "0.02em",
    color: "#5e4734",
    whiteSpace: "nowrap",
  },
  scorePadLabelLeft: {
    alignSelf: "flex-start",
    textAlign: "center",
    width: "100%",
    transform: "translateX(18%)",
  },
  scorePadLabelRight: {
    alignSelf: "flex-end",
    textAlign: "center",
    width: "100%",
    transform: "translateX(-18%)",
  },
  scorePadValue: {
    marginTop: "4%",
    fontSize: "clamp(16px, 1.1rem, 20px)",
    lineHeight: 1,
    fontWeight: 900,
    color: "#2f241b",
    width: "100%",
  },
  scorePadValueLeft: {
    textAlign: "center",
    transform: "translateX(18%)",
  },
  scorePadValueRight: {
    textAlign: "center",
    transform: "translateX(-18%)",
  },
  scorePadMetaLabel: {
    fontSize: "clamp(14px, 0.96rem, 16px)",
    lineHeight: 1,
    fontWeight: 900,
    color: "#70543c",
    whiteSpace: "nowrap",
  },
  scorePadMetaLabelLeft: {
    alignSelf: "flex-start",
    textAlign: "center",
    width: "100%",
    transform: "translateX(18%)",
  },
  scorePadMetaLabelRight: {
    alignSelf: "flex-end",
    textAlign: "center",
    width: "100%",
    transform: "translateX(-18%)",
  },
  scorePadMetaValue: {
    marginTop: "4%",
    fontSize: "clamp(15px, 1rem, 18px)",
    lineHeight: 1,
    fontWeight: 900,
    color: "#33271d",
    width: "100%",
  },
  scorePadMetaValueLeft: {
    textAlign: "center",
    transform: "translateX(18%)",
  },
  scorePadMetaValueRight: {
    textAlign: "center",
    transform: "translateX(-18%)",
  },
  tablePanelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    marginBottom: "18px",
    flexWrap: "wrap",
  },
  tableTitle: {
    fontSize: "24px",
    fontWeight: 700,
    marginBottom: "4px",
  },
  tableSubtitle: {
    color: "#64748b",
    fontSize: "14px",
  },
  roundPill: {
    borderRadius: "999px",
    padding: "10px 14px",
    background: "#0f172a",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 700,
  },
  board: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  topSeat: {
    display: "flex",
    justifyContent: "center",
  },
  middleSeatsRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 280px",
    gap: "16px",
    alignItems: "stretch",
  },
  sideSeat: {
    display: "flex",
    alignItems: "center",
  },
  playerSeat: {
    width: "100%",
    borderRadius: "14px",
    padding: "10px 12px",
    background: "rgba(248,250,252,0.92)",
    border: "1px solid rgba(213,220,230,0.7)",
    boxSizing: "border-box",
  },
  playerSeatActive: {
    border: "2px solid #0f172a",
    background: "#eef2ff",
  },
  playerSeatHuman: {
    background: "#f7fbf7",
  },
  playerSeatTopRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    alignItems: "center",
    marginBottom: "8px",
  },
  playerSeatName: {
    fontWeight: 700,
    fontSize: "14px",
  },
  playerSeatDetail: {
    color: "#475569",
    fontSize: "12px",
    marginBottom: "6px",
  },
  turnIndicator: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#1d4ed8",
  },
  teamBadge: {
    padding: "4px 10px",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 700,
  },
  teamBadgeUs: {
    background: "#dcfce7",
    color: "#166534",
  },
  teamBadgeThem: {
    background: "#fee2e2",
    color: "#991b1b",
  },
  tableSurface: {
    background: "linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(255,255,255,0.02) 100%)",
    borderRadius: "28px",
    aspectRatio: "1 / 1",
    minHeight: 0,
    height: "100%",
    maxHeight: "100%",
    padding: "clamp(6px, 0.8vw, 10px)",
    boxSizing: "border-box",
    width: "auto",
    maxWidth: "100%",
    border: "1px solid rgba(255,255,255,0.08)",
    alignSelf: "center",
    transform: "scale(1.08)",
    transformOrigin: "center center",
  },
  tableSurfaceWrap: {
    flex: 1.32,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  playerCardsBlock: {
    borderRadius: "18px",
    background: "transparent",
    padding: "clamp(4px, 0.38vw, 6px) clamp(9px, 0.82vw, 11px) clamp(6px, 0.54vw, 8px)",
    border: "1px solid rgba(255,255,255,0.03)",
    flexShrink: 0,
    minHeight: "clamp(78px, 7.2vw, 96px)",
    overflow: "visible",
  },
  tableHudSidebar: {
    height: "100%",
    borderRadius: "20px",
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.03)",
    padding: "clamp(9px, 0.82vw, 12px) clamp(9px, 0.88vw, 12px)",
    boxSizing: "border-box",
    display: "grid",
    gridTemplateRows: "max-content max-content",
    gap: "clamp(10px, 0.82vw, 12px)",
    justifyItems: "center",
    alignItems: "center",
    alignContent: "center",
    color: "#f8fafc",
    minHeight: 0,
    overflow: "hidden",
  },
  tableHudScoreRow: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    fontSize: "15px",
    fontWeight: 800,
    flexWrap: "wrap",
  },
  tableHudStats: {
    borderRadius: "16px",
    background: "linear-gradient(180deg, rgba(109,72,48,0.78) 0%, rgba(57,36,24,0.84) 100%)",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: "clamp(11px, 0.88vw, 13px) clamp(12px, 1vw, 14px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "clamp(9px, 0.7vw, 11px)",
    width: "90%",
    alignSelf: "center",
    justifySelf: "center",
    marginTop: "clamp(2px, 0.2vw, 4px)",
    minHeight: 0,
    height: "100%",
  },
  tableHudStatsDivider: {
    width: "72%",
    height: "1px",
    background:
      "linear-gradient(90deg, rgba(255,244,228,0.04) 0%, rgba(255,244,228,0.32) 50%, rgba(255,244,228,0.04) 100%)",
    alignSelf: "center",
  },
  tableHudStatLine: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
    fontSize: "clamp(9px, 0.82vw, 10px)",
    alignItems: "baseline",
    color: "#f8f2e8",
    textShadow: "0 1px 2px rgba(0,0,0,0.7)",
    lineHeight: 1.2,
  },
  tableHudStatLabel: {
    color: "rgba(255,244,228,0.88)",
    fontSize: "clamp(8px, 0.72vw, 9px)",
    fontWeight: 700,
    letterSpacing: "0.01em",
    textShadow: "0 1px 2px rgba(0,0,0,0.58)",
    flex: "0 0 34%",
  },
  tableHudStatValue: {
    color: "#fffaf2",
    fontSize: "clamp(10px, 0.94vw, 11px)",
    fontWeight: 800,
    textAlign: "right",
    marginLeft: "auto",
    textShadow: "0 1px 2px rgba(0,0,0,0.82)",
    flex: 1,
  },
  tableHudStatLineCentered: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "clamp(4px, 0.3vw, 5px)",
    textAlign: "center",
    lineHeight: 1.2,
  },
  tableHudStatLabelCentered: {
    color: "rgba(255,244,228,0.9)",
    fontSize: "clamp(8px, 0.72vw, 9px)",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    textShadow: "0 1px 2px rgba(0,0,0,0.58)",
  },
  tableHudStatValueCentered: {
    color: "#fffaf2",
    fontSize: "clamp(12px, 1.1vw, 15px)",
    fontWeight: 900,
    textAlign: "center",
    textShadow: "0 1px 2px rgba(0,0,0,0.82)",
    lineHeight: 1.12,
    maxWidth: "100%",
  },
  tableHudVenue: {
    borderRadius: "14px",
    background: "rgba(0,0,0,0.18)",
    padding: "clamp(6px, 0.6vw, 8px)",
  },
  tableHudVenueTitle: {
    fontSize: "clamp(10px, 0.82vw, 12px)",
    fontWeight: 800,
    marginBottom: "4px",
  },
  tableHudVenueText: {
    fontSize: "clamp(8px, 0.72vw, 10px)",
    color: "rgba(248,250,252,0.86)",
    lineHeight: 1.45,
  },
  tableHudMessage: {
    borderRadius: "14px",
    background: "rgba(0,0,0,0.18)",
    padding: "clamp(6px, 0.6vw, 8px)",
    fontSize: "clamp(8px, 0.72vw, 10px)",
    lineHeight: 1.4,
    color: "#fff7ed",
    minHeight: "clamp(26px, 2.3vw, 32px)",
  },
  actionDisplayCard: {
    borderRadius: "18px",
    background: "linear-gradient(180deg, #f3e7cf 0%, #dec49c 100%)",
    border: "1px solid #b18553",
    padding: "clamp(9px, 0.74vw, 11px) clamp(11px, 0.96vw, 13px)",
    color: "#2f241b",
    boxShadow: "0 8px 18px rgba(0,0,0,0.18)",
    width: "90%",
    alignSelf: "center",
    justifySelf: "center",
    minHeight: "clamp(76px, 6.9vw, 94px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  actionDisplayLabel: {
    fontSize: "clamp(8px, 0.7vw, 10px)",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: "5px",
    textAlign: "center",
  },
  actionDisplayValue: {
    fontSize: "clamp(13px, 1.12vw, 17px)",
    fontWeight: 900,
    lineHeight: 1.1,
    textAlign: "center",
  },
  tableCenterArea: {
    width: "100%",
    height: "100%",
    minHeight: "360px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tableMiddleRow: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "1fr 140px 1fr",
    gap: "18px",
    alignItems: "center",
  },
  tableCenterBadge: {
    borderRadius: "999px",
    background: "rgba(255,255,255,0.12)",
    color: "#fff",
    padding: "16px 10px",
    textAlign: "center",
    border: "1px solid rgba(255,255,255,0.18)",
  },
  tableCenterBadgeTop: {
    fontSize: "20px",
    fontWeight: 800,
    letterSpacing: "0.06em",
  },
  tableCenterBadgeBottom: {
    fontSize: "13px",
    marginTop: "6px",
  },
  tableCardSlot: {
    width: "120px",
    minHeight: "150px",
    borderRadius: "16px",
    background: "rgba(255,255,255,0.12)",
    border: "1px dashed rgba(255,255,255,0.35)",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px",
    boxSizing: "border-box",
  },
  tableCardSlotHighlight: {
    boxShadow: "0 0 0 3px #fde68a",
    background: "rgba(255,255,255,0.18)",
  },
  tableCardSlotHeader: {
    fontSize: "12px",
    marginBottom: "8px",
    opacity: 0.95,
  },
  tableCardFace: {
    width: "92px",
    minHeight: "116px",
    background: "#ffffff",
    color: "#111827",
    borderRadius: "12px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px",
    boxSizing: "border-box",
    border: "1px solid #dbe2ea",
    boxShadow: "0 8px 18px rgba(0,0,0,0.18)",
  },
  tableCardRank: {
    fontSize: "28px",
    fontWeight: 800,
    lineHeight: 1,
  },
  tableCardSuit: {
    fontSize: "30px",
    lineHeight: 1,
  },
  tableCardText: {
    fontSize: "12px",
    color: "#475569",
  },
  tableCardEmpty: {
    fontSize: "14px",
    opacity: 0.9,
    textAlign: "center",
  },
  bottomSeatBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  actionArea: {
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    borderRadius: "20px",
    background: "rgba(255,255,255,0.94)",
    padding: "14px",
    marginTop: "14px",
  },
  mobileHandPanel: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    minHeight: "100%",
  },
  mobileHandHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  mobileHandTitle: {
    fontSize: "clamp(10px, 0.82vw, 12px)",
    fontWeight: 800,
    color: "#fff7ed",
  },
  mobileHandMeta: {
    fontSize: "clamp(8px, 0.65vw, 9px)",
    fontWeight: 700,
    color: "#d6c7b2",
  },
  mobileHandRow: {
    display: "flex",
    gap: "clamp(4px, 0.35vw, 6px)",
    flexWrap: "nowrap",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingTop: "clamp(2px, 0.2vw, 4px)",
  },
  inGameActionsCard: {
    borderRadius: "16px",
    background: "linear-gradient(180deg, rgba(25,16,11,0.22) 0%, rgba(17,10,7,0.34) 100%)",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: "clamp(7px, 0.58vw, 9px)",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(9px, 0.72vw, 11px)",
    width: "90%",
    alignSelf: "center",
    justifySelf: "center",
    marginTop: "clamp(10px, 0.92vw, 14px)",
    transform: "translateY(0)",
  },
  inGameActionsRow: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(8px, 0.62vw, 10px)",
    alignItems: "stretch",
    width: "100%",
  },
  inGameActionsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "clamp(8px, 0.62vw, 10px)",
    justifyItems: "stretch",
    width: "100%",
  },
  inGameActionsHint: {
    borderRadius: "12px",
    background: "rgba(255,255,255,0.08)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "#fff7ed",
    padding: "clamp(6px, 0.55vw, 7px)",
    fontSize: "clamp(8px, 0.72vw, 9px)",
    lineHeight: 1.45,
  },
  mobileCardButton: {
    width: "clamp(40px, 3.6vw, 50px)",
    minWidth: "clamp(40px, 3.6vw, 50px)",
    minHeight: "clamp(58px, 5.2vw, 72px)",
    borderRadius: "8px",
    background: `center / cover no-repeat url(${cardFaceAgedPaperAsset})`,
    border: "1px solid #d9c7a8",
    boxShadow: "0 4px 10px rgba(15,23,42,0.12)",
    padding: "clamp(3px, 0.28vw, 4px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    cursor: "pointer",
  },
  mobileCardCornerTop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    lineHeight: 1,
  },
  mobileCardCornerBottom: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    lineHeight: 1,
    transform: "rotate(180deg)",
  },
  mobileCardRank: {
    fontSize: "clamp(11px, 0.9vw, 13px)",
    fontWeight: 800,
    lineHeight: 1,
  },
  mobileCardSuit: {
    fontSize: "clamp(11px, 0.96vw, 13px)",
    lineHeight: 1,
  },
  mobileCardCenterSuit: {
    fontSize: "clamp(16px, 1.36vw, 20px)",
    lineHeight: 1,
    alignSelf: "center",
  },
  actionAreaHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  actionAreaTitle: {
    fontSize: "20px",
    fontWeight: 700,
    marginBottom: "4px",
  },
  actionAreaSubtitle: {
    fontSize: "14px",
    color: "#64748b",
  },
  betBadge: {
    borderRadius: "999px",
    padding: "10px 14px",
    background: "#7c2d12",
    color: "#fff",
    fontWeight: 700,
    fontSize: "14px",
  },
  trucoPanel: {
    borderRadius: "18px",
    padding: "16px",
    background: "#fff7ed",
    border: "1px solid #fed7aa",
  },
  trucoPanelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
    marginBottom: "12px",
  },
  trucoPanelTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#9a3412",
  },
  trucoPanelStatus: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#7c2d12",
    background: "#ffedd5",
    borderRadius: "999px",
    padding: "6px 10px",
  },
  trucoPanelBody: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  trucoMessageBox: {
    borderRadius: "12px",
    padding: "12px",
    background: "#ffffff",
    border: "1px solid #fed7aa",
  },
  trucoMessageLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#9a3412",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "6px",
  },
  trucoMessageText: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#431407",
  },
  trucoDetailsGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  gap: "10px",
  },
  trucoDetailCard: {
    borderRadius: "12px",
    padding: "12px",
    background: "#ffffff",
    border: "1px solid #fed7aa",
  },

  trucoDetailLabel: {
    fontSize: "12px",
    fontWeight: 700,
    color: "#9a3412",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: "6px",
  },

  trucoDetailValue: {
    fontSize: "15px",
    fontWeight: 700,
    color: "#431407",
  },
  trucoActionsRow: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  trucoPrimaryButton: {
    padding: "clamp(6px, 0.5vw, 8px) clamp(11px, 0.96vw, 14px)",
    borderRadius: "12px",
    border: "none",
    backgroundColor: "transparent",
    color: "#fff",
    cursor: "pointer",
    fontSize: "clamp(10px, 0.88vw, 11px)",
    fontWeight: 800,
    minHeight: "clamp(34px, 2.8vw, 38px)",
    lineHeight: 1.05,
    textShadow: "0 1px 2px rgba(0,0,0,0.72)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    marginLeft: 0,
    marginRight: 0,
  },
  trucoSecondaryButton: {
    padding: "clamp(6px, 0.5vw, 8px) clamp(11px, 0.96vw, 14px)",
    borderRadius: "12px",
    border: "none",
    backgroundColor: "transparent",
    color: "#f7efe0",
    cursor: "pointer",
    fontSize: "clamp(10px, 0.88vw, 11px)",
    fontWeight: 800,
    minHeight: "clamp(34px, 2.8vw, 38px)",
    lineHeight: 1.05,
    textShadow: "0 1px 2px rgba(0,0,0,0.72)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minWidth: 0,
    alignSelf: "stretch",
    marginLeft: 0,
    marginRight: 0,
  },
  trucoHintBox: {
    borderRadius: "12px",
    padding: "12px 14px",
    background: "#fff",
    border: "1px dashed #fdba74",
    color: "#7c2d12",
    fontSize: "14px",
  },
  handPanel: {
    borderRadius: "18px",
    padding: "16px",
    background: "#f8fafc",
    border: "1px solid #dbe2ea",
  },
  handTitle: {
    fontSize: "18px",
    fontWeight: 700,
    marginBottom: "12px",
  },
  emptyHandBox: {
    borderRadius: "12px",
    padding: "16px",
    background: "#fff",
    border: "1px solid #e2e8f0",
    color: "#475569",
  },
  handRow: {
    display: "flex",
    justifyContent: "center",
    gap: "16px",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  cardButton: {
    width: "120px",
    height: "170px",
    borderRadius: "14px",
    border: "1px solid #d8dee6",
    background: "#ffffff",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "10px",
    textAlign: "left",
    transition: "transform 0.15s ease, box-shadow 0.15s ease",
    boxShadow: "0 8px 16px rgba(15, 23, 42, 0.08)",
  },
  cardButtonActive: {
    cursor: "pointer",
  },
  cardButtonDisabled: {
    opacity: 0.65,
    cursor: "not-allowed",
  },
  cardCornerTop: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    lineHeight: 1,
    gap: "4px",
  },
  cardCenterSuit: {
    alignSelf: "center",
    fontSize: "42px",
    lineHeight: 1,
  },
  cardCornerBottom: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    lineHeight: 1,
    gap: "4px",
  },
  cardRank: {
    fontSize: "30px",
    fontWeight: 800,
  },
  cardSuit: {
    fontSize: "22px",
  },
  actionHintBox: {
    borderRadius: "12px",
    padding: "12px 14px",
    background: "#fff",
    border: "1px solid #e2e8f0",
    color: "#334155",
    fontSize: "15px",
  },
  gameStartScreen: {
    width: "100%",
    height: "100%",
    display: "flex",
    position: "relative",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "clamp(14px, 1.4vw, 24px)",
    boxSizing: "border-box",
    gap: "clamp(16px, 2vw, 28px)",
  },
  gameStartCard: {
    width: "min(100%, 460px)",
    borderRadius: "22px",
    background: "linear-gradient(180deg, rgba(58,42,31,0.95) 0%, rgba(28,20,14,0.95) 100%)",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: "clamp(18px, 2vw, 28px)",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(10px, 1.1vw, 14px)",
    color: "#fff7ed",
    boxShadow: "0 18px 34px rgba(0,0,0,0.28)",
  },
  gameStartTopActionButton: {
    position: "absolute",
    top: "clamp(14px, 1.2vw, 20px)",
    right: "clamp(14px, 1.2vw, 20px)",
    borderRadius: "999px",
    border: "1px solid rgba(244, 226, 190, 0.36)",
    background: "linear-gradient(180deg, rgba(72,48,32,0.92) 0%, rgba(34,23,16,0.92) 100%)",
    color: "#fff7ed",
    padding: "10px 16px",
    fontSize: "12px",
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    cursor: "pointer",
    boxShadow: "0 12px 24px rgba(0,0,0,0.24)",
  },
  gameStartEyebrow: {
    fontSize: "clamp(11px, 0.95vw, 13px)",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#d8c3a5",
  },
  gameStartTitle: {
    margin: 0,
    fontSize: "clamp(26px, 2.4vw, 34px)",
    lineHeight: 1.05,
  },
  gameStartVenue: {
    fontSize: "clamp(18px, 1.6vw, 22px)",
    fontWeight: 800,
  },
  gameStartVenueMeta: {
    fontSize: "clamp(12px, 1vw, 14px)",
    color: "#d8c3a5",
    lineHeight: 1.45,
  },
  gameStartDebugPanel: {
    borderRadius: "16px",
    background: "rgba(0, 0, 0, 0.16)",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  gameStartDebugLabel: {
    fontSize: "12px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#f3e7cf",
  },
  gameStartDebugSelect: {
    width: "100%",
    borderRadius: "12px",
    border: "1px solid rgba(244, 226, 190, 0.22)",
    background: "rgba(255,255,255,0.08)",
    color: "#fff7ed",
    padding: "10px 12px",
    fontSize: "14px",
    fontWeight: 700,
    boxSizing: "border-box",
  },
  gameStartDebugHint: {
    fontSize: "12px",
    lineHeight: 1.45,
    color: "#d8c3a5",
  },
  gameStartOptions: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "clamp(10px, 1vw, 12px)",
    margin: "6px 0 10px 0",
  },
  gameStartOption: {
    borderRadius: "16px",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.06)",
    color: "#fff7ed",
    padding: "clamp(12px, 1.15vw, 16px)",
    fontSize: "clamp(13px, 1.05vw, 15px)",
    fontWeight: 700,
    cursor: "pointer",
  },
  gameStartOptionActive: {
    background: "linear-gradient(180deg, #f3e7cf 0%, #dec49c 100%)",
    color: "#2f241b",
    border: "1px solid #b18553",
  },
  gameStartResetButton: {
    borderRadius: "18px",
    border: "1px solid rgba(244, 226, 190, 0.4)",
    background: "linear-gradient(180deg, rgba(86,58,39,0.94) 0%, rgba(49,33,22,0.94) 100%)",
    color: "#fff7ed",
    padding: "clamp(14px, 1.3vw, 18px) clamp(18px, 1.7vw, 24px)",
    fontSize: "clamp(16px, 1.4vw, 20px)",
    fontWeight: 800,
    boxShadow: "0 16px 28px rgba(0,0,0,0.24)",
    cursor: "pointer",
    alignSelf: "center",
    minWidth: "clamp(220px, 24vw, 300px)",
  },
  gameStartLaunchButton: {
    borderRadius: "18px",
    border: "1px solid rgba(15, 23, 42, 0.22)",
    background: "linear-gradient(180deg, #17213d 0%, #0f172a 100%)",
    color: "#fff7ed",
    padding: "clamp(14px, 1.3vw, 18px) clamp(18px, 1.7vw, 24px)",
    fontSize: "clamp(18px, 1.55vw, 22px)",
    fontWeight: 900,
    boxShadow: "0 16px 28px rgba(0,0,0,0.24)",
    cursor: "pointer",
    alignSelf: "center",
    minWidth: "clamp(220px, 24vw, 300px)",
  },
  gameStartActionsStack: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(10px, 1vw, 14px)",
    alignSelf: "center",
  },
  gameStartResetButtonCentered: {
    margin: "0 auto",
  },
  characterSelectScreen: {
    gridColumn: "1 / -1",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(8px, 0.75vw, 12px)",
    padding: "clamp(10px, 0.95vw, 14px)",
    boxSizing: "border-box",
    minWidth: 0,
    minHeight: 0,
  },
  venueIntroScreen: {
    gridColumn: "1 / -1",
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(10px, 0.9vw, 14px)",
    padding: "clamp(12px, 1vw, 16px)",
    boxSizing: "border-box",
    minWidth: 0,
    minHeight: 0,
  },
  venueIntroHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
  },
  venueIntroEyebrow: {
    fontSize: "clamp(11px, 0.92vw, 13px)",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    color: "#cda05f",
  },
  venueIntroTitle: {
    margin: "6px 0 4px 0",
    fontSize: "clamp(24px, 2.1vw, 32px)",
    lineHeight: 1.02,
    color: "#f6ead8",
    fontFamily: "Georgia, serif",
  },
  venueIntroMeta: {
    fontSize: "clamp(12px, 0.95vw, 14px)",
    color: "#d5bf9a",
  },
  venueIntroBoard: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(0, 1.1fr)",
    gap: "clamp(10px, 0.9vw, 16px)",
  },
  venueIntroMainCard: {
    borderRadius: "22px",
    padding: "clamp(16px, 1.4vw, 22px)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    background: "linear-gradient(180deg, rgba(54,36,24,0.94) 0%, rgba(26,17,11,0.96) 100%)",
    border: "1px solid rgba(205, 160, 95, 0.18)",
    color: "#f8e7cb",
    boxShadow: "0 18px 34px rgba(0,0,0,0.22)",
  },
  venueIntroSectionLabel: {
    fontSize: "12px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#d5bf9a",
  },
  venueIntroLead: {
    margin: 0,
    fontSize: "clamp(17px, 1.35vw, 21px)",
    lineHeight: 1.35,
    fontWeight: 700,
    color: "#fff2df",
  },
  venueIntroText: {
    margin: 0,
    fontSize: "clamp(13px, 1vw, 15px)",
    lineHeight: 1.55,
    color: "#e7d3b4",
  },
  venueIntroFactsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "10px",
    marginTop: "auto",
  },
  venueIntroFactCard: {
    borderRadius: "16px",
    padding: "12px 14px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  venueIntroFactLabel: {
    fontSize: "11px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#cfb48b",
  },
  venueIntroFactValue: {
    fontSize: "clamp(15px, 1.15vw, 18px)",
    color: "#fff4e3",
  },
  venueIntroRosterPanel: {
    borderRadius: "22px",
    padding: "clamp(16px, 1.4vw, 22px)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    background: "linear-gradient(180deg, rgba(29,18,12,0.94) 0%, rgba(16,10,7,0.97) 100%)",
    border: "1px solid rgba(205, 160, 95, 0.18)",
    boxShadow: "0 18px 34px rgba(0,0,0,0.22)",
    minHeight: 0,
  },
  venueIntroParticipants: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "10px",
    overflow: "auto",
    paddingRight: "4px",
  },
  venueIntroParticipantCard: {
    display: "grid",
    gridTemplateColumns: "72px minmax(0, 1fr)",
    gap: "10px",
    alignItems: "start",
    borderRadius: "18px",
    padding: "10px",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  venueIntroParticipantAvatar: {
    width: "72px",
    aspectRatio: "1 / 1.16",
    borderRadius: "14px",
    overflow: "hidden",
    background: "rgba(0,0,0,0.22)",
  },
  venueIntroParticipantImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  venueIntroParticipantBody: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: 0,
  },
  venueIntroParticipantRole: {
    fontSize: "11px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    color: "#cda05f",
  },
  venueIntroParticipantName: {
    fontSize: "16px",
    fontWeight: 800,
    lineHeight: 1.05,
    color: "#f7e7cf",
  },
  venueIntroParticipantText: {
    fontSize: "12px",
    lineHeight: 1.45,
    color: "#d6c3a5",
  },
  venueIntroActions: {
    display: "flex",
    justifyContent: "center",
    paddingTop: "4px",
  },
  characterSelectHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
  },
  characterSelectEyebrow: {
    fontSize: "clamp(12px, 1vw, 18px)",
    lineHeight: 0.92,
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "#cda05f",
    fontFamily: "Georgia, serif",
    maxWidth: "180px",
  },
  characterSelectBackButton: {
    borderRadius: "999px",
    border: "1px solid rgba(244, 226, 190, 0.28)",
    background: "rgba(18, 12, 8, 0.76)",
    color: "#f8e7cb",
    padding: "8px 14px",
    fontSize: "11px",
    fontWeight: 800,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    cursor: "pointer",
  },
  characterSelectBoard: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "minmax(226px, 0.66fr) minmax(0, 1.34fr)",
    gap: "clamp(10px, 0.95vw, 16px)",
    padding: "clamp(6px, 0.55vw, 10px)",
    borderRadius: "24px",
    border: "1px solid rgba(203, 159, 96, 0.14)",
    background: "linear-gradient(180deg, rgba(30,18,11,0.86) 0%, rgba(19,11,7,0.88) 100%)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.03)",
    alignItems: "stretch",
    overflow: "hidden",
  },
  characterSelectLeftColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "clamp(8px, 0.75vw, 12px)",
    padding: "clamp(6px, 0.55vw, 10px) clamp(2px, 0.3vw, 6px) clamp(6px, 0.55vw, 10px) 0",
    borderRight: "1px solid rgba(205, 160, 95, 0.16)",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  characterPortraitFrame: {
    position: "relative",
    width: "min(100%, 236px)",
    maxWidth: "100%",
    aspectRatio: "3 / 4",
    borderRadius: "22px",
    overflow: "hidden",
    border: "1px solid rgba(205, 160, 95, 0.32)",
    background: "linear-gradient(180deg, rgba(25,16,10,0.95) 0%, rgba(12,8,5,0.95) 100%)",
    boxShadow: "0 18px 34px rgba(0,0,0,0.26), inset 0 1px 0 rgba(255,255,255,0.06)",
    alignSelf: "center",
    flexShrink: 0,
  },
  characterPortraitImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  characterPortraitOverlay: {
    position: "absolute",
    inset: "auto 0 0 0",
    padding: "14px 12px 12px",
    background:
      "linear-gradient(180deg, rgba(16,10,7,0) 0%, rgba(16,10,7,0.76) 34%, rgba(16,10,7,0.94) 100%)",
  },
  characterPortraitName: {
    fontSize: "clamp(20px, 1.5vw, 27px)",
    lineHeight: 0.98,
    fontWeight: 800,
    color: "#e7bc7a",
    fontFamily: "Georgia, serif",
    textWrap: "balance",
  },
  characterPortraitNickname: {
    marginTop: "6px",
    fontSize: "clamp(12px, 0.9vw, 16px)",
    fontStyle: "italic",
    color: "#f4dfbf",
    fontFamily: "Georgia, serif",
  },
  characterIdentityPanel: {
    width: "min(100%, 236px)",
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "clamp(6px, 0.5vw, 10px)",
    padding: "clamp(8px, 0.62vw, 12px)",
    borderRadius: "22px",
    border: "1px solid rgba(205, 160, 95, 0.22)",
    background:
      "linear-gradient(180deg, rgba(46,30,20,0.92) 0%, rgba(28,18,12,0.94) 100%)",
    boxShadow: "0 14px 28px rgba(0,0,0,0.16)",
    boxSizing: "border-box",
    minWidth: 0,
  },
  characterIdentityBlock: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "6px",
    textAlign: "left",
  },
  characterName: {
    fontSize: "clamp(34px, 2.8vw, 48px)",
    lineHeight: 0.96,
    fontWeight: 800,
    color: "#e0b069",
    fontFamily: "Georgia, serif",
    textWrap: "balance",
  },
  characterNickname: {
    fontSize: "clamp(18px, 1.5vw, 26px)",
    fontStyle: "italic",
    color: "#f1d7ad",
    fontFamily: "Georgia, serif",
  },
  characterNavigator: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "clamp(12px, 1vw, 18px)",
    width: "100%",
  },
  characterNavButton: {
    width: "34px",
    height: "34px",
    borderRadius: "999px",
    border: "1px solid rgba(205, 160, 95, 0.36)",
    background: "linear-gradient(180deg, rgba(85,57,37,0.92) 0%, rgba(43,28,18,0.92) 100%)",
    color: "#f6e5c7",
    fontSize: "18px",
    fontWeight: 900,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  characterNavDots: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "5px",
    flex: 1,
    minWidth: 0,
  },
  characterNavDot: {
    width: "7px",
    height: "7px",
    borderRadius: "999px",
    background: "rgba(205,160,95,0.24)",
  },
  characterNavDotActive: {
    width: "8px",
    height: "8px",
    background: "#d7a85f",
    boxShadow: "0 0 0 2px rgba(215,168,95,0.16)",
  },
  characterNavCounter: {
    alignSelf: "center",
    fontSize: "10px",
    color: "#a77d4a",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  characterSelectRightColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(8px, 0.65vw, 12px)",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
  },
  characterContextHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    minWidth: 0,
  },
  characterContextKicker: {
    color: "#cda05f",
    fontWeight: 800,
    fontSize: "clamp(11px, 0.82vw, 13px)",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    marginBottom: "4px",
  },
  characterContextLabel: {
    color: "#d3b185",
    fontStyle: "italic",
    fontWeight: 700,
    fontSize: "clamp(12px, 0.84vw, 14px)",
    lineHeight: 1.35,
    maxWidth: "none",
  },
  characterInfoPanel: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: "clamp(8px, 0.65vw, 12px)",
    padding: 0,
    overflow: "hidden",
  },
  characterInfoCard: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(6px, 0.5vw, 10px)",
    padding: "clamp(10px, 0.78vw, 14px)",
    borderRadius: "22px",
    background:
      "linear-gradient(180deg, rgba(43,28,18,0.92) 0%, rgba(26,17,12,0.95) 100%)",
    border: "1px solid rgba(205,160,95,0.22)",
    boxShadow: "0 18px 34px rgba(0,0,0,0.18)",
    boxSizing: "border-box",
    minWidth: 0,
    width: "100%",
    overflow: "hidden",
    flexShrink: 0,
  },
  characterDetailsGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 0.9fr) minmax(0, 1.1fr)",
    gap: "clamp(8px, 0.65vw, 12px)",
    minWidth: 0,
  },
  characterInfoSection: {
    display: "flex",
    flexDirection: "column",
    gap: "clamp(6px, 0.5vw, 10px)",
    minWidth: 0,
    minHeight: 0,
  },
  characterInfoTitle: {
    fontSize: "clamp(14px, 1vw, 18px)",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#cda05f",
    fontFamily: "Georgia, serif",
  },
  characterStoryQuote: {
    borderLeft: "3px solid rgba(205,160,95,0.46)",
    paddingLeft: "12px",
    color: "#efd6ad",
    fontSize: "clamp(14px, 1vw, 17px)",
    lineHeight: 1.42,
    fontStyle: "italic",
    fontFamily: "Georgia, serif",
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    paddingRight: "6px",
    maxHeight: "100%",
  },
  characterStyleChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  characterStyleChip: {
    borderRadius: "999px",
    border: "1px solid rgba(184, 131, 63, 0.42)",
    background: "rgba(116,72,32,0.2)",
    color: "#f0d2a2",
    padding: "6px 10px",
    fontSize: "11px",
    fontWeight: 800,
    fontFamily: "Georgia, serif",
  },
  characterAttributeRow: {
    display: "grid",
    gridTemplateColumns: "max-content minmax(0, 1fr) max-content",
    alignItems: "center",
    gap: "10px",
  },
  characterAttributeLabel: {
    fontSize: "clamp(12px, 0.88vw, 15px)",
    fontWeight: 800,
    color: "#efdfc3",
    fontFamily: "Georgia, serif",
  },
  characterAttributeTrack: {
    height: "10px",
    borderRadius: "999px",
    background: "rgba(58,31,17,0.9)",
    border: "1px solid rgba(205,160,95,0.28)",
    overflow: "hidden",
  },
  characterAttributeFill: {
    height: "100%",
    borderRadius: "999px",
    background: "linear-gradient(90deg, #b87424 0%, #e1b45f 100%)",
    boxShadow: "0 0 14px rgba(225,180,95,0.22)",
  },
  characterAttributeValue: {
    fontSize: "clamp(11px, 0.8vw, 13px)",
    fontWeight: 800,
    color: "#f2ddb8",
  },
  characterActionFooter: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "clamp(8px, 0.65vw, 12px)",
    borderRadius: "22px",
    border: "1px solid rgba(205,160,95,0.18)",
    background:
      "linear-gradient(180deg, rgba(33,21,14,0.9) 0%, rgba(20,13,9,0.94) 100%)",
    minWidth: 0,
    width: "100%",
    boxSizing: "border-box",
    flexShrink: 0,
  },
  characterSelectActionButton: {
    borderRadius: "16px",
    border: "1px solid rgba(205,160,95,0.34)",
    background: "linear-gradient(180deg, rgba(96,63,40,0.96) 0%, rgba(54,34,22,0.96) 100%)",
    color: "#f7ebd4",
    padding: "11px 14px",
    fontSize: "clamp(12px, 0.92vw, 15px)",
    fontWeight: 900,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    boxShadow: "0 16px 28px rgba(0,0,0,0.2)",
    cursor: "pointer",
  },
  characterSelectEmptyBox: {
    margin: "auto",
    borderRadius: "20px",
    padding: "24px 28px",
    background: "rgba(25,16,10,0.84)",
    border: "1px solid rgba(205,160,95,0.22)",
    color: "#f8e7cb",
    fontSize: "18px",
    fontWeight: 700,
  },
  logsCard: {
    background: "#ffffff",
    border: "1px solid #d8dee6",
    borderRadius: "18px",
    padding: "16px",
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.06)",
  },
  logsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "12px",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "22px",
  },
  logsArea: {
    width: "100%",
    minHeight: "260px",
    resize: "vertical",
    boxSizing: "border-box",
    fontFamily: "monospace",
    fontSize: "12px",
    padding: "12px",
    borderRadius: "12px",
    border: "1px solid #d8dee6",
    background: "#f8fafc",
  },
}

export default App  
